---
title: "MP3"
author: "Cassie Naranjo"
date: "4/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(sf)
library(macleish)
library(leaflet)
```

```{r}
macleish_layers[["landmarks"]] %>%
  plot()
```
Location of Parking Lot 
```{r}
parking <- data.frame(lat = 42.448013, lon = -72.68066)
base_plot <- leaflet() %>%
  addTiles() %>%
  addMarkers(lng = ~lon, lat = ~lat, data = parking,
             popup = "Parking Lot")
base_plot
```
Location of Group Campsite 
```{r}
group_campsite <- data.frame(lat = 42.450976, lon = -72.678154)
base_plot <- leaflet() %>%
  addTiles() %>%
  addMarkers(lng = ~lon, lat = ~lat, data = group_campsite,
             popup = "Group Campsite")
base_plot
```
Location of Remote Campsite
```{r}
remote_campsite <- data.frame(lat = 42.458549, lon = -72.679581)
base_plot <- leaflet() %>%
  addTiles() %>%
  addMarkers(lng = ~lon, lat = ~lat, data = remote_campsite,
             popup = "Remote Campsite")
base_plot
```

Plot of all 3 sites 
```{r}
base_plot <- leaflet() %>%
  addTiles() %>%
  addMarkers(lng = ~lon, lat = ~lat, data = group_campsite,
             popup = "Group Campsite") %>%
  addMarkers(lng = ~lon, lat = ~lat, data = remote_campsite,
             popup = "Remote Campsite") %>%
  addMarkers(lng = ~lon, lat = ~lat, data = parking,
             popup = "Parking Lot") 
  base_plot
```

```{r}
boundary <- macleish_layers %>% 
  pluck("boundary")

base_plot %>%
  addPolygons(data = boundary, color = "black")
```

hahahahahahahah